/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author IVAN
 */
public class MenuAdminView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public MenuAdminView() {
        initComponents();
        this.setResizable(false);
        this.setSize(1030, 600);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_menu = new javax.swing.JPanel();
        btn_logout = new javax.swing.JButton();
        js_5 = new javax.swing.JSeparator();
        jpanel_salario = new javax.swing.JPanel();
        btn_salario = new javax.swing.JButton();
        lb_salario = new javax.swing.JLabel();
        js_4 = new javax.swing.JSeparator();
        jpanel_ventas = new javax.swing.JPanel();
        btn_ventas = new javax.swing.JButton();
        lb_ventas = new javax.swing.JLabel();
        js_3 = new javax.swing.JSeparator();
        jpanel_empleado = new javax.swing.JPanel();
        btn_empleado = new javax.swing.JButton();
        lb_empleado = new javax.swing.JLabel();
        js_1 = new javax.swing.JSeparator();
        jpanel_sucursal = new javax.swing.JPanel();
        btn_sucursal = new javax.swing.JButton();
        lb_sucursal = new javax.swing.JLabel();
        js_2 = new javax.swing.JSeparator();
        jpanel_home = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        lb_home = new javax.swing.JLabel();
        jpanel_header = new javax.swing.JPanel();
        lb_rol = new javax.swing.JLabel();
        lb_user = new javax.swing.JLabel();
        lb_iconUser = new javax.swing.JLabel();
        panelSlider = new rojerusan.RSPanelsSlider();
        jp_home = new javax.swing.JPanel();
        lb_logo = new javax.swing.JLabel();
        lb_bienvenido = new javax.swing.JLabel();
        lb_userHome = new javax.swing.JLabel();
        jp_sucursal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_nuevaSucursal = new javax.swing.JButton();
        lb_nuevaSucursal = new javax.swing.JLabel();
        jscroll_sucursal = new javax.swing.JScrollPane();
        jtable_sucursal = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_buscarSucursal = new javax.swing.JTextField();
        btn_buscarSucursal = new javax.swing.JButton();
        jp_empleado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_nuevoEmpleado = new javax.swing.JButton();
        lb_nuevoEmpleado = new javax.swing.JLabel();
        jscroll_empleado = new javax.swing.JScrollPane();
        jtable_empleado = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_buscarEmpleado = new javax.swing.JTextField();
        btn_buscarEmpleado = new javax.swing.JButton();
        jp_ventas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jscroll_ventas = new javax.swing.JScrollPane();
        jtable_ventas = new javax.swing.JTable();
        cbox_mes = new javax.swing.JComboBox<>();
        cbox_anio = new javax.swing.JComboBox<>();
        btn_generarReporteMensual = new javax.swing.JButton();
        jp_salario = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jscroll_salario = new javax.swing.JScrollPane();
        jtable_salario = new javax.swing.JTable();
        cbox_mesSalario = new javax.swing.JComboBox<>();
        cbox_anioSalario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jpanel_menu.setBackground(new java.awt.Color(48, 71, 94));
        jpanel_menu.setLayout(null);

        btn_logout.setBackground(new java.awt.Color(240, 84, 84));
        btn_logout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btn_logout.png"))); // NOI18N
        btn_logout.setBorder(null);
        btn_logout.setBorderPainted(false);
        btn_logout.setContentAreaFilled(false);
        jpanel_menu.add(btn_logout);
        btn_logout.setBounds(10, 520, 80, 30);

        js_5.setForeground(new java.awt.Color(255, 255, 255));
        jpanel_menu.add(js_5);
        js_5.setBounds(0, 500, 100, 10);

        jpanel_salario.setOpaque(false);
        jpanel_salario.setLayout(null);

        btn_salario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cash.png"))); // NOI18N
        btn_salario.setBorder(null);
        btn_salario.setBorderPainted(false);
        btn_salario.setContentAreaFilled(false);
        jpanel_salario.add(btn_salario);
        btn_salario.setBounds(26, 20, 48, 48);

        lb_salario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_salario.setForeground(new java.awt.Color(255, 255, 255));
        lb_salario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_salario.setText("Salario");
        jpanel_salario.add(lb_salario);
        lb_salario.setBounds(10, 70, 80, 20);

        jpanel_menu.add(jpanel_salario);
        jpanel_salario.setBounds(0, 400, 100, 100);

        js_4.setForeground(new java.awt.Color(255, 255, 255));
        jpanel_menu.add(js_4);
        js_4.setBounds(0, 400, 100, 10);

        jpanel_ventas.setOpaque(false);
        jpanel_ventas.setLayout(null);

        btn_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bill.png"))); // NOI18N
        btn_ventas.setBorder(null);
        btn_ventas.setBorderPainted(false);
        btn_ventas.setContentAreaFilled(false);
        jpanel_ventas.add(btn_ventas);
        btn_ventas.setBounds(26, 20, 48, 48);

        lb_ventas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_ventas.setForeground(new java.awt.Color(255, 255, 255));
        lb_ventas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ventas.setText("Ventas");
        jpanel_ventas.add(lb_ventas);
        lb_ventas.setBounds(10, 70, 80, 20);

        jpanel_menu.add(jpanel_ventas);
        jpanel_ventas.setBounds(0, 300, 100, 100);

        js_3.setForeground(new java.awt.Color(255, 255, 255));
        jpanel_menu.add(js_3);
        js_3.setBounds(0, 300, 100, 10);

        jpanel_empleado.setOpaque(false);
        jpanel_empleado.setLayout(null);

        btn_empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/employee.png"))); // NOI18N
        btn_empleado.setBorder(null);
        btn_empleado.setBorderPainted(false);
        btn_empleado.setContentAreaFilled(false);
        jpanel_empleado.add(btn_empleado);
        btn_empleado.setBounds(26, 20, 48, 48);

        lb_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_empleado.setForeground(new java.awt.Color(255, 255, 255));
        lb_empleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_empleado.setText("Empleado");
        jpanel_empleado.add(lb_empleado);
        lb_empleado.setBounds(10, 70, 80, 20);

        jpanel_menu.add(jpanel_empleado);
        jpanel_empleado.setBounds(0, 200, 100, 100);

        js_1.setForeground(new java.awt.Color(255, 255, 255));
        jpanel_menu.add(js_1);
        js_1.setBounds(0, 200, 100, 10);

        jpanel_sucursal.setOpaque(false);
        jpanel_sucursal.setLayout(null);

        btn_sucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/building.png"))); // NOI18N
        btn_sucursal.setBorder(null);
        btn_sucursal.setBorderPainted(false);
        btn_sucursal.setContentAreaFilled(false);
        jpanel_sucursal.add(btn_sucursal);
        btn_sucursal.setBounds(26, 20, 48, 48);

        lb_sucursal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_sucursal.setForeground(new java.awt.Color(255, 255, 255));
        lb_sucursal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_sucursal.setText("Sucursal");
        jpanel_sucursal.add(lb_sucursal);
        lb_sucursal.setBounds(10, 70, 80, 20);

        jpanel_menu.add(jpanel_sucursal);
        jpanel_sucursal.setBounds(0, 100, 100, 100);

        js_2.setForeground(new java.awt.Color(255, 255, 255));
        jpanel_menu.add(js_2);
        js_2.setBounds(0, 100, 100, 10);

        jpanel_home.setOpaque(false);
        jpanel_home.setLayout(null);

        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btn_home.setBorder(null);
        btn_home.setBorderPainted(false);
        btn_home.setContentAreaFilled(false);
        jpanel_home.add(btn_home);
        btn_home.setBounds(26, 20, 48, 48);

        lb_home.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_home.setForeground(new java.awt.Color(255, 255, 255));
        lb_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_home.setText("Inicio");
        jpanel_home.add(lb_home);
        lb_home.setBounds(20, 70, 60, 20);

        jpanel_menu.add(jpanel_home);
        jpanel_home.setBounds(0, 0, 100, 100);

        getContentPane().add(jpanel_menu);
        jpanel_menu.setBounds(0, 0, 100, 570);

        jpanel_header.setBackground(new java.awt.Color(34, 40, 49));
        jpanel_header.setLayout(null);

        lb_rol.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lb_rol.setForeground(new java.awt.Color(255, 255, 255));
        lb_rol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_rol.setText("Administrador");
        jpanel_header.add(lb_rol);
        lb_rol.setBounds(30, 20, 180, 30);

        lb_user.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lb_user.setForeground(new java.awt.Color(255, 255, 255));
        lb_user.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_user.setText("Admin");
        jpanel_header.add(lb_user);
        lb_user.setBounds(440, 20, 390, 30);

        lb_iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        jpanel_header.add(lb_iconUser);
        lb_iconUser.setBounds(840, 10, 48, 48);

        getContentPane().add(jpanel_header);
        jpanel_header.setBounds(100, 0, 930, 70);

        panelSlider.setBackground(new java.awt.Color(232, 232, 232));

        jp_home.setBackground(new java.awt.Color(255, 255, 255));
        jp_home.setName("home"); // NOI18N
        jp_home.setLayout(null);

        lb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo_home.png"))); // NOI18N
        jp_home.add(lb_logo);
        lb_logo.setBounds(290, 10, 350, 300);

        lb_bienvenido.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lb_bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_bienvenido.setText("¡Bienvenido...!");
        jp_home.add(lb_bienvenido);
        lb_bienvenido.setBounds(10, 320, 910, 50);

        lb_userHome.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lb_userHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_userHome.setText("Ivan");
        jp_home.add(lb_userHome);
        lb_userHome.setBounds(10, 380, 910, 50);

        panelSlider.add(jp_home, "card1");

        jp_sucursal.setBackground(new java.awt.Color(255, 255, 255));
        jp_sucursal.setName("sucursal"); // NOI18N
        jp_sucursal.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sucursal");
        jp_sucursal.add(jLabel1);
        jLabel1.setBounds(10, 10, 900, 50);

        btn_nuevaSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        btn_nuevaSucursal.setBorder(null);
        btn_nuevaSucursal.setBorderPainted(false);
        btn_nuevaSucursal.setContentAreaFilled(false);
        jp_sucursal.add(btn_nuevaSucursal);
        btn_nuevaSucursal.setBounds(90, 110, 32, 32);

        lb_nuevaSucursal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_nuevaSucursal.setText("Nueva sucursal");
        jp_sucursal.add(lb_nuevaSucursal);
        lb_nuevaSucursal.setBounds(130, 110, 150, 30);

        jtable_sucursal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtable_sucursal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jscroll_sucursal.setViewportView(jtable_sucursal);

        jp_sucursal.add(jscroll_sucursal);
        jscroll_sucursal.setBounds(50, 240, 840, 140);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setOpaque(true);
        jp_sucursal.add(jLabel2);
        jLabel2.setBounds(530, 135, 260, 3);

        txt_buscarSucursal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_buscarSucursal.setToolTipText("");
        txt_buscarSucursal.setBorder(null);
        txt_buscarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarSucursalActionPerformed(evt);
            }
        });
        jp_sucursal.add(txt_buscarSucursal);
        txt_buscarSucursal.setBounds(540, 105, 240, 30);

        btn_buscarSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btn_buscar.png"))); // NOI18N
        btn_buscarSucursal.setBorder(null);
        btn_buscarSucursal.setBorderPainted(false);
        btn_buscarSucursal.setContentAreaFilled(false);
        jp_sucursal.add(btn_buscarSucursal);
        btn_buscarSucursal.setBounds(800, 105, 80, 32);

        panelSlider.add(jp_sucursal, "card2");

        jp_empleado.setBackground(new java.awt.Color(255, 255, 255));
        jp_empleado.setName("empleado"); // NOI18N
        jp_empleado.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Empleado");
        jp_empleado.add(jLabel3);
        jLabel3.setBounds(10, 10, 910, 50);

        btn_nuevoEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        btn_nuevoEmpleado.setBorder(null);
        btn_nuevoEmpleado.setBorderPainted(false);
        btn_nuevoEmpleado.setContentAreaFilled(false);
        jp_empleado.add(btn_nuevoEmpleado);
        btn_nuevoEmpleado.setBounds(90, 110, 32, 32);

        lb_nuevoEmpleado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_nuevoEmpleado.setText("Nuevo empleado");
        jp_empleado.add(lb_nuevoEmpleado);
        lb_nuevoEmpleado.setBounds(130, 110, 260, 30);

        jscroll_empleado.setBackground(new java.awt.Color(255, 255, 255));

        jtable_empleado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtable_empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jscroll_empleado.setViewportView(jtable_empleado);

        jp_empleado.add(jscroll_empleado);
        jscroll_empleado.setBounds(20, 240, 890, 140);

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setOpaque(true);
        jp_empleado.add(jLabel4);
        jLabel4.setBounds(530, 135, 260, 3);

        txt_buscarEmpleado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_buscarEmpleado.setToolTipText("");
        txt_buscarEmpleado.setBorder(null);
        jp_empleado.add(txt_buscarEmpleado);
        txt_buscarEmpleado.setBounds(540, 105, 240, 30);

        btn_buscarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btn_buscar.png"))); // NOI18N
        btn_buscarEmpleado.setBorder(null);
        btn_buscarEmpleado.setBorderPainted(false);
        btn_buscarEmpleado.setContentAreaFilled(false);
        jp_empleado.add(btn_buscarEmpleado);
        btn_buscarEmpleado.setBounds(800, 105, 80, 32);

        panelSlider.add(jp_empleado, "card3");

        jp_ventas.setBackground(new java.awt.Color(255, 255, 255));
        jp_ventas.setName("ventas"); // NOI18N
        jp_ventas.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ventas");
        jp_ventas.add(jLabel5);
        jLabel5.setBounds(10, 10, 910, 50);

        jtable_ventas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtable_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jscroll_ventas.setViewportView(jtable_ventas);

        jp_ventas.add(jscroll_ventas);
        jscroll_ventas.setBounds(50, 240, 840, 140);

        jp_ventas.add(cbox_mes);
        cbox_mes.setBounds(710, 130, 130, 30);

        cbox_anio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021" }));
        jp_ventas.add(cbox_anio);
        cbox_anio.setBounds(80, 130, 130, 30);

        btn_generarReporteMensual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btn_generarReporteMensual.png"))); // NOI18N
        btn_generarReporteMensual.setBorder(null);
        btn_generarReporteMensual.setBorderPainted(false);
        btn_generarReporteMensual.setContentAreaFilled(false);
        jp_ventas.add(btn_generarReporteMensual);
        btn_generarReporteMensual.setBounds(290, 180, 350, 40);

        panelSlider.add(jp_ventas, "card4");

        jp_salario.setBackground(new java.awt.Color(255, 255, 255));
        jp_salario.setName("salario"); // NOI18N
        jp_salario.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Salario");
        jp_salario.add(jLabel6);
        jLabel6.setBounds(10, 20, 900, 50);

        jtable_salario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtable_salario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jscroll_salario.setViewportView(jtable_salario);

        jp_salario.add(jscroll_salario);
        jscroll_salario.setBounds(50, 240, 840, 140);

        jp_salario.add(cbox_mesSalario);
        cbox_mesSalario.setBounds(680, 160, 140, 30);

        cbox_anioSalario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021" }));
        jp_salario.add(cbox_anioSalario);
        cbox_anioSalario.setBounds(120, 160, 140, 30);

        panelSlider.add(jp_salario, "card5");

        getContentPane().add(panelSlider);
        panelSlider.setBounds(100, 70, 930, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarSucursalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_buscarEmpleado;
    public javax.swing.JButton btn_buscarSucursal;
    public javax.swing.JButton btn_empleado;
    public javax.swing.JButton btn_generarReporteMensual;
    public javax.swing.JButton btn_home;
    public javax.swing.JButton btn_logout;
    public javax.swing.JButton btn_nuevaSucursal;
    public javax.swing.JButton btn_nuevoEmpleado;
    public javax.swing.JButton btn_salario;
    public javax.swing.JButton btn_sucursal;
    public javax.swing.JButton btn_ventas;
    public javax.swing.JComboBox<String> cbox_anio;
    public javax.swing.JComboBox<String> cbox_anioSalario;
    public javax.swing.JComboBox<String> cbox_mes;
    public javax.swing.JComboBox<String> cbox_mesSalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jp_empleado;
    public javax.swing.JPanel jp_home;
    public javax.swing.JPanel jp_salario;
    public javax.swing.JPanel jp_sucursal;
    public javax.swing.JPanel jp_ventas;
    private javax.swing.JPanel jpanel_empleado;
    private javax.swing.JPanel jpanel_header;
    private javax.swing.JPanel jpanel_home;
    private javax.swing.JPanel jpanel_menu;
    private javax.swing.JPanel jpanel_salario;
    private javax.swing.JPanel jpanel_sucursal;
    private javax.swing.JPanel jpanel_ventas;
    private javax.swing.JSeparator js_1;
    private javax.swing.JSeparator js_2;
    private javax.swing.JSeparator js_3;
    private javax.swing.JSeparator js_4;
    private javax.swing.JSeparator js_5;
    private javax.swing.JScrollPane jscroll_empleado;
    private javax.swing.JScrollPane jscroll_salario;
    private javax.swing.JScrollPane jscroll_sucursal;
    private javax.swing.JScrollPane jscroll_ventas;
    public javax.swing.JTable jtable_empleado;
    public javax.swing.JTable jtable_salario;
    public javax.swing.JTable jtable_sucursal;
    public javax.swing.JTable jtable_ventas;
    private javax.swing.JLabel lb_bienvenido;
    private javax.swing.JLabel lb_empleado;
    private javax.swing.JLabel lb_home;
    private javax.swing.JLabel lb_iconUser;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JLabel lb_nuevaSucursal;
    private javax.swing.JLabel lb_nuevoEmpleado;
    private javax.swing.JLabel lb_rol;
    private javax.swing.JLabel lb_salario;
    private javax.swing.JLabel lb_sucursal;
    public javax.swing.JLabel lb_user;
    public javax.swing.JLabel lb_userHome;
    private javax.swing.JLabel lb_ventas;
    public rojerusan.RSPanelsSlider panelSlider;
    public javax.swing.JTextField txt_buscarEmpleado;
    public javax.swing.JTextField txt_buscarSucursal;
    // End of variables declaration//GEN-END:variables
}
